
name: Write png NODD

on: workflow_dispatch

jobs:
  write_png:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: 'write'
      id-token: 'write'
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v6
      
    # - name: Print dir tree
    #   run: tree

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    # - name: 'Authenticate to Google Cloud'
    #   uses: 'google-github-actions/auth@v3'
    #   with:
    #     # You'll get these strings after setting up WIF in the GCP Console
    #     workload_identity_provider: 'projects/933817670224/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
    #     service_account: 'ce-github-sa1@ggn-nmfs-usamlr-dev-7b99.iam.gserviceaccount.com'

    - name: Run Python script
      shell: bash -el {0}
      run: python Write_NODD_png.py